const peopleData = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    phone: "555-123-4567",
    candidate: "confirmed",
    country: "USA",
  },
  {
    id: 2,
    name: "Brian Smith",
    email: "brian.smith@example.com",
    phone: "555-234-5678",
    candidate: "confirmed",
    country: "Canada",
  },
  {
    id: 3,
    name: "Carla Martinez",
    email: "carla.m@example.com",
    phone: "555-345-6789",
    candidate: "false",
    country: "Mexico",
  },
  {
    id: 4,
    name: "David Nguyen",
    email: "d.nguyen@example.com",
    phone: "555-456-7890",
    candidate: "confirmed",
    country: "Vietnam",
  },
  {
    id: 5,
    name: "Ella Thompson",
    email: "ella.t@example.com",
    phone: "555-567-8901",
    candidate: "false",
    country: "UK",
  },
  {
    id: 6,
    name: "Felix Moore",
    email: "felix.moore@example.com",
    phone: "555-678-9012",
    candidate: "false",
    country: "Australia",
  },
  {
    id: 7,
    name: "Grace Lee",
    email: "grace.lee@example.com",
    phone: "555-789-0123",
    candidate: "confirmed",
    country: "South Korea",
  },
  {
    id: 8,
    name: "Henry Kim",
    email: "henry.k@example.com",
    phone: "555-890-1234",
    candidate: "false",
    country: "South Korea",
  },
  {
    id: 9,
    name: "Isabella Rivera",
    email: "isabella.r@example.com",
    phone: "555-901-2345",
    candidate: "false",
    country: "Spain",
  },
  {
    id: 10,
    name: "Jack Patel",
    email: "jack.p@example.com",
    phone: "555-012-3456",
    candidate: "confirmed",
    country: "India",
  },
  {
    id: 11,
    name: "Karen Wilson",
    email: "karen.wilson@example.com",
    phone: "555-112-2334",
    candidate: "confirmed",
    country: "USA",
  },
  {
    id: 12,
    name: "Liam Cooper",
    email: "liam.cooper@example.com",
    phone: "555-223-3445",
    candidate: "Special Patient",
    country: "UK",
  },
  {
    id: 13,
    name: "Maya Scott",
    email: "maya.scott@example.com",
    phone: "555-334-4556",
    candidate: "false",
    country: "Australia",
  },
  {
    id: 14,
    name: "Nathan Young",
    email: "nathan.young@example.com",
    phone: "555-445-5667",
    candidate: "confirmed",
    country: "Canada",
  },
  {
    id: 15,
    name: "Olivia Martinez",
    email: "olivia.m@example.com",
    phone: "555-556-6778",
    candidate: "Special Patient",
    country: "Mexico",
  },
  {
    id: 16,
    name: "Paul Edwards",
    email: "paul.edwards@example.com",
    phone: "555-667-7889",
    candidate: "false",
    country: "USA",
  },
  {
    id: 17,
    name: "Quinn Baker",
    email: "quinn.baker@example.com",
    phone: "555-778-8990",
    candidate: "confirmed",
    country: "Ireland",
  },
  {
    id: 18,
    name: "Rachel Green",
    email: "rachel.green@example.com",
    phone: "555-889-9001",
    candidate: "Special Patient",
    country: "UK",
  },
  {
    id: 19,
    name: "Steven Wright",
    email: "steven.wright@example.com",
    phone: "555-990-0112",
    candidate: "false",
    country: "USA",
  },
  {
    id: 20,
    name: "Tina Adams",
    email: "tina.adams@example.com",
    phone: "555-101-1213",
    candidate: "confirmed",
    country: "Australia",
  },
  // More people with countries added:
  {
    id: 21,
    name: "Uma Patel",
    email: "uma.patel@example.com",
    phone: "555-121-3141",
    candidate: "Special Patient",
    country: "India",
  },
  {
    id: 22,
    name: "Victor Chan",
    email: "victor.chan@example.com",
    phone: "555-131-4151",
    candidate: "confirmed",
    country: "Hong Kong",
  },
  {
    id: 23,
    name: "Wendy Davis",
    email: "wendy.davis@example.com",
    phone: "555-141-5161",
    candidate: "false",
    country: "USA",
  },
  {
    id: 24,
    name: "Xavier Lopez",
    email: "xavier.lopez@example.com",
    phone: "555-151-6171",
    candidate: "confirmed",
    country: "Spain",
  },
  {
    id: 25,
    name: "Yara Hassan",
    email: "yara.hassan@example.com",
    phone: "555-161-7181",
    candidate: "suspected",
    country: "Egypt",
  },
  {
    id: 26,
    name: "Zane Cooper",
    email: "zane.cooper@example.com",
    phone: "555-171-8191",
    candidate: "false",
    country: "New Zealand",
  },
  {
    id: 27,
    name: "Amelia Jones",
    email: "amelia.jones@example.com",
    phone: "555-181-9202",
    candidate: "confirmed",
    country: "UK",
  },
  {
    id: 28,
    name: "Ben Thompson",
    email: "ben.thompson@example.com",
    phone: "555-192-0212",
    candidate: "suspected",
    country: "USA",
  },
  {
    id: 29,
    name: "Cecilia Morales",
    email: "cecilia.morales@example.com",
    phone: "555-202-1222",
    candidate: "false",
    country: "Argentina",
  },
  {
    id: 30,
    name: "Derek Fisher",
    email: "derek.fisher@example.com",
    phone: "555-212-2232",
    candidate: "confirmed",
    country: "Canada",
  },
  {
    id: 31,
    name: "Erika Svensson",
    email: "erika.svensson@example.com",
    phone: "555-222-3242",
    candidate: "suspected",
    country: "Sweden",
  },
  {
    id: 32,
    name: "Felipe Gonzalez",
    email: "felipe.gonzalez@example.com",
    phone: "555-232-4252",
    candidate: "false",
    country: "Chile",
  },
  {
    id: 33,
    name: "Gina Rodriguez",
    email: "gina.rodriguez@example.com",
    phone: "555-242-5262",
    candidate: "confirmed",
    country: "Puerto Rico",
  },
  {
    id: 34,
    name: "Hassan Ali",
    email: "hassan.ali@example.com",
    phone: "555-252-6272",
    candidate: "suspected",
    country: "UAE",
  },
  {
    id: 35,
    name: "Ivy Zhang",
    email: "ivy.zhang@example.com",
    phone: "555-262-7282",
    candidate: "false",
    country: "China",
  },
  {
    id: 36,
    name: "Jason Clark",
    email: "jason.clark@example.com",
    phone: "555-272-8292",
    candidate: "confirmed",
    country: "USA",
  },
  {
    id: 37,
    name: "Katrina Bell",
    email: "katrina.bell@example.com",
    phone: "555-282-9303",
    candidate: "suspected",
    country: "New Zealand",
  },
  {
    id: 38,
    name: "Leo Martin",
    email: "leo.martin@example.com",
    phone: "555-292-0313",
    candidate: "false",
    country: "France",
  },
  {
    id: 39,
    name: "Mina Park",
    email: "mina.park@example.com",
    phone: "555-303-1323",
    candidate: "confirmed",
    country: "South Korea",
  },
  {
    id: 40,
    name: "Noah Wilson",
    email: "noah.wilson@example.com",
    phone: "555-313-2333",
    candidate: "suspected",
    country: "USA",
  },
];

export default peopleData;
